export const CATEGORIES_LOAD = 'CATEGORIES_LOAD';
export const CATEGORIES_LOAD_SUCCESS = 'CATEGORIES_LOAD_SUCCESS';
export const CATEGORIES_LOAD_FAIL = 'CATEGORIES_LOAD_FAIL';
export const CATEGORY_LOAD = 'CATEGORY_LOAD';
export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS';
export const CATEGORY_LOAD_FAIL = 'CATEGORY_LOAD_FAIL';
export const ACTIVATE_CATEGORY = 'ACTIVATE_CATEGORY';

export const PHOTOS_LOAD = 'PHOTOS_LOAD';
export const PHOTOS_LOAD_SUCCESS = 'PHOTOS_LOAD_SUCCESS';
export const PHOTOS_LOAD_FAIL = 'PHOTOS_LOAD_FAIL';
export const ACTIVATE_PHOTO = 'ACTIVATE_PHOTO';


export const PAGES_LOAD = 'PAGES_LOAD';
export const PAGES_LOAD_SUCCESS = 'PAGES_LOAD_SUCCESS';
export const PAGES_LOAD_FAIL = 'PAGES_LOAD_FAIL';
export const PAGE_LOAD = 'PAGE_LOAD';
export const PAGE_LOAD_SUCCESS = 'PAGE_LOAD_SUCCESS';
export const PAGE_LOAD_FAIL = 'PAGE_LOAD_FAIL';
export const ACTIVATE_PAGE = 'ACTIVATE_PAGE';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';
export const AUTH_LOAD_FAIL = 'AUTH_LOAD_FAIL';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
